/**
 * imClaw WhatsApp Department & Specialized Agents
 * Integrates WhatsApp operations (signals, sales, group management, token delivery)
 * directly into the imClaw Organization Engine.
 */

import { ImClawEventBus } from "../../../platform/events/event-bus.js";
import { WhatsAppCapability, type WhatsAppCapabilityResponse } from "./whatsapp-capability.js";

export const INTEGRAL_MARKET_GROUPS = {
  COMMUNITY_PARENT: "120363410674864635@g.us",
  VIP_SIGNALS: "120363412887543171@g.us",
  VIP_SALES_SUPPORT: "120363430275762821@g.us",
  VIP_COMMUNITY_NEWS: "120363430672666018@g.us",
  COMMUNITY_ANNOUNCEMENTS: "120363430710697460@g.us",
} as const;

export class WhatsAppDepartmentManager {
  private capability: WhatsAppCapability;
  public readonly eventBus?: ImClawEventBus;

  constructor(capability?: WhatsAppCapability, eventBus?: ImClawEventBus) {
    this.capability = capability ?? new WhatsAppCapability();
    this.eventBus = eventBus;
  }

  /**
   * SignalManagementAgent — Dispatches approved signals to authorized WhatsApp groups.
   */
  public async handleSignalDispatch(
    signal: { symbol: string; direction: "BUY" | "SELL"; entry: number; sl: number; tp: number },
    targetGroupId: string = INTEGRAL_MARKET_GROUPS.VIP_SIGNALS,
  ): Promise<WhatsAppCapabilityResponse> {
    const text = `🚨 *INTEGRAL MARKET SIGNAL* 🚨\n\n*Symbol*: ${signal.symbol}\n*Action*: ${signal.direction}\n*Entry*: ${signal.entry}\n*Stop Loss*: ${signal.sl}\n*Take Profit*: ${signal.tp}\n\n_Auto-generated by Market Sensei • Governed by Risk Engine_`;

    return this.capability.execute({
      action: "SEND_SIGNAL",
      agentId: "wa-signal-agent",
      sessionName: "default",
      recipientOrGroupId: targetGroupId,
      payload: { text, signalId: `${signal.symbol}-${Date.now()}` },
      requiresApproval: true,
    });
  }

  /**
   * WhatsAppSalesAgent — Engages incoming leads and sends qualification responses.
   */
  public async handleSalesInquiry(
    senderPhoneOrGroup: string = INTEGRAL_MARKET_GROUPS.VIP_SALES_SUPPORT,
    inquiryText: string,
  ): Promise<WhatsAppCapabilityResponse> {
    const text = `💼 *Integral Market AI Sales & Client Desk*\n\nHello! Regarding: "${inquiryText}"\n\nI am the autonomous AI Client Onboarding Specialist for Integral Market. We provide institutional copy trading, automated algorithms, and premium algorithmic execution.\n\nReply directly or contact support to get started!`;

    return this.capability.execute({
      action: "SEND_TEXT",
      agentId: "wa-sales-agent",
      sessionName: "default",
      recipientOrGroupId: senderPhoneOrGroup,
      payload: { text },
      requiresApproval: false, // Auto-reply lead intake
    });
  }

  /**
   * Community & News Agent — Dispatches news and economic alerts.
   */
  public async handleNewsBroadcast(
    headline: string,
    body: string,
    targetGroupId: string = INTEGRAL_MARKET_GROUPS.VIP_COMMUNITY_NEWS,
  ): Promise<WhatsAppCapabilityResponse> {
    const text = `📢 *INTEGRAL MARKET INTEL & NEWS* 📰\n\n*${headline}*\n\n${body}\n\n_Dispatched autonomously by imClaw Community Agent_`;

    return this.capability.execute({
      action: "SEND_TEXT",
      agentId: "wa-community-news-agent",
      sessionName: "default",
      recipientOrGroupId: targetGroupId,
      payload: { text },
      requiresApproval: false,
    });
  }

  /**
   * ClientAuthTokenDelivery — Delivers short-lived, single-use authentication tokens to verified clients.
   */
  public async deliverClientAuthToken(
    clientPhone: string,
    clientId: string,
    token: string,
  ): Promise<WhatsAppCapabilityResponse> {
    const text = `🔐 *Integral Market Security Alert*\n\nYour one-time portal access token is:\n*${token}*\n\nThis token expires in 10 minutes. Never share this code with anyone.`;

    return this.capability.execute({
      action: "SEND_AUTH_TOKEN",
      agentId: "wa-auth-delivery-agent",
      sessionName: "default",
      recipientOrGroupId: clientPhone,
      payload: { text, clientId, tokenType: "OTP_AUTH" },
      requiresApproval: true, // Mandatory approval for security credentials
    });
  }
}
